### ISSUE TITLE
For Deepstream 6.2

### ISSUE THREAD

**Issue by Shabbir-9916** [sylvain-prevost/nvdsgst_infer-wsl2#1]
When can we expect the updated repo for DeepStream 6.2?

**Comment by sylvain-prevost** [comment]
Hi, 

My final device target is the 'old' Jetson Nano device, so I never had a good reason to try out anything beyond DS 6.0.1 (as DS6.1/6.2 are, per doc, not supported on the old nano).

I'll download DS6.2, check the status vs WSL debugging and EGL (maybe it now works out of box?), and let you know.

**Comment by paleomoon** [comment]
Expecting your update, DS 6.1 can't run on WSL2, [it's said](https://forums.developer.nvidia.com/t/i-cant-make-wsl2-run-with-any-deepstream-app-sample/189271) in the plan, but still not yet.

**Comment by sylvain-prevost** [comment]
I finally took a bit of time to test it out - see https://github.com/sylvain-prevost/deepstream_wsl
enjoy.
