### ISSUE TITLE
It Ok in deepstream-test1 but wrong in deepstream-test1-rtsp-out

### ISSUE THREAD

**Issue by swo026** [sylvain-prevost/nvdsgst_infer-wsl2#2]
When I exec ` python3 deepstream_test1_rtsp_out.py -i vtest.avi`
I got 
```
Error: gst-resource-error-quark: Could not open device '/dev/nvhost-msenc' for reading and writing. (7): v4l2_calls.c(653): gst_v4l2_open (): /GstPipeline:pipeline0/nvv4l2h264enc:encoder:
system error: No such file or directory

**Comment by sylvain-prevost** [comment]
Given that nvv4l2decoder is problematic, I'm not surprised that it is also the case with the corresponding encoder. I would suggest to try using a slightly different pipeline to perform the RTSP encoding (maybe leveraging 'x264enc')
